"""Creat Order

Revision ID: 62dff535ec29
Revises: 9c24f97ed062
Create Date: 2024-04-14 19:21:23.540368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "62dff535ec29"
down_revision: Union[str, None] = "9c24f97ed062"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("number", sa.String(length=255), nullable=False),
        sa.Column("customer", sa.UUID(), nullable=False),
        sa.Column("responsible", sa.UUID(), nullable=False),
        sa.Column("cell", sa.Integer(), nullable=False),
        sa.Column("storage_period", sa.Interval(), nullable=False),
        sa.Column("placement_date", sa.DateTime(), nullable=False),
        sa.Column("small", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cell"],
            ["cell.id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["responsible"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_order_id"), "order", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_id"), table_name="order")
    op.drop_table("order")
    # ### end Alembic commands ###
